config/routes.rb
AxiomJvpSite::Application.routes.draw do
  resources :login2s

  namespace :jvp do
    resources :logins
    root :to => 'logins#index'
  end

  namespace :axiom do
    resources :login

  end

  resources :saml
  post "saml/consume"

end

app/models/account.rb
require 'lib/onelogin/ruby-saml/settings'

class Account < ActiveRecord::Base

  def Account.get_saml_settings
    # should retrieve SAML-settings based on subdomain, IP-address, NameID or similar
    settings = Onelogin::Saml::Settings.new


    settings.assertion_consumer_service_url   = 'http://corpappsdev.careerbuilder.com/saml/consume'
    settings.issuer                           = 'http://corpappsdev.careerbuilder.com'
    settings.idp_sso_target_url               = 'https://cbtest.okta.com/app/template_saml_2_0/k4lymtarUFNMMBSZZSOI/sso/saml'
    settings.idp_cert_fingerprint             =  '02:05:79:D8:96:CC:CA:54:2F:16:E2:6E:7D:32:F3:54:95:61:89:71'
    settings.name_identifier_format           = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

    settings
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :force_plugin_reload

  def force_plugin_reload
    ActiveSupport::Dependencies.load_file "xml_sec.rb" if "development" == ENV
    ActiveSupport::Dependencies.load_file "xmlcanonicalizer.rb" if "development" == ENV
  end

end

app/controllers/axiom/login_controller.rb
class Axiom::LoginController < ApplicationController
  def index
    #@settings = Account.get_saml_settings()
    #
    #if @settings.nil?
    #  return redirect_to '/saml'
    #end

    # If we're viewing this unauthenticated, set our goback URL for after logging in
    if session[:userid].nil?
      #session[:goback_to] = request.url
      session[:userid]=nil
      return redirect_to '/saml'

    end
    respond_to do |format|
      format.html # index.html.erb
    end

  end
end

app/controllers/jvp/logins_controller.rb
class Jvp::LoginsController < ApplicationController
  # GET /logins
  # GET /logins.json
  def index
    #@logins = Login.all

    respond_to do |format|
      format.html # index.html.erb

    end
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/new
  # GET /logins/new.json
  def new
    @login = Login.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @login }
    end
  end

  # GET /logins/1/edit
  def edit
    @login = Login.find(params[:id])
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(params[:login])

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render json: @login, status: :created, location: @login }
      else
        format.html { render action: "new" }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logins/1
  # PUT /logins/1.json
  def update
    @login = Login.find(params[:id])

    respond_to do |format|
      if @login.update_attributes(params[:login])
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login = Login.find(params[:id])
    @login.destroy

    respond_to do |format|
      format.html { redirect_to logins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/saml_controller.rb
require 'onelogin/ruby-saml/settings'
require 'onelogin/ruby-saml/authrequest'
require 'onelogin/ruby-saml/response'

class SamlController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:consume]

  def index
    # insert identity provider discovery logic here
    settings = get_saml_settings
    request = Onelogin::Saml::Authrequest.new
    redirect_to(request.create(settings))
  end

  def consume

    response = Onelogin::Saml::Response.new(params[:SAMLResponse])

    # insert identity provider discovery logic here
    response.settings = get_saml_settings

    logger.info "NAMEID: #{response.name_id}"

    if response.is_valid?
      session[:userid] = response.name_id
      redirect_to '/axiom/login'
    else
      redirect_to :action => :fail
    end
  end

  def get_saml_settings
    # should retrieve SAML-settings based on subdomain, IP-address, NameID or similar
    settings = Onelogin::Saml::Settings.new


    settings.assertion_consumer_service_url   = 'http://corpappsdev.careerbuilder.com/saml/consume'
    settings.issuer                           = 'http://corpappsdev.careerbuilder.com'
    settings.idp_sso_target_url               = 'https://cbtest.okta.com/app/template_saml_2_0/k4lymtarUFNMMBSZZSOI/sso/saml'
    settings.idp_cert_fingerprint             =  '02:05:79:D8:96:CC:CA:54:2F:16:E2:6E:7D:32:F3:54:95:61:89:71'
    settings.name_identifier_format           = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

    settings
  end

  def complete

  end

  def fail
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/axiom/login_helper.rb
module Axiom::LoginHelper
end

app/helpers/axiom/saml_helper.rb
module Axiom::SamlHelper
end

app/helpers/login2s_helper.rb
module Login2sHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/axiom/login/index.html.erb
<p>Authenticated Axiom User through SAML</p>
<%=session[:userid] %>

app/views/axiom/saml/index.html.erb
<p>index</p>

app/views/jvp/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jvp/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/jvp/logins/index.html.erb
<h1>JVP Login</h1>

<table>
  <tr>

    <th></th>
    <th></th>
  </tr>

  <tr>
    <td>Login: <%= text_field_tag('Login','login')%></td>
    </tr>
  <tr>
    <td>Password:<%= password_field_tag('Password','password') %></td>

  </tr>

</table>

<%= button_tag 'Sign in'%>

app/views/jvp/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/jvp/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @login.userid %>
</p>

<p>
  <b>Password:</b>
  <%= @login.password %>
</p>


<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AxiomJvpSite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login2s/_form.html.erb
<%= form_for(@login2) do |f| %>
  <% if @login2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login2.errors.count, "error") %> prohibited this login2 from being saved:</h2>

      <ul>
      <% @login2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/login2s/edit.html.erb
<h1>Editing login2</h1>

<%= render 'form' %>

<%= link_to 'Show', @login2 %> |
<%= link_to 'Back', login2s_path %>

app/views/login2s/index.html.erb
<h1>Listing login2s</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @login2s.each do |login2| %>
  <tr>
    <td><%= login2.userid %></td>
    <td><%= login2.password %></td>
    <td><%= link_to 'Show', login2 %></td>
    <td><%= link_to 'Edit', edit_login2_path(login2) %></td>
    <td><%= link_to 'Destroy', login2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Login2', new_login2_path %>

app/views/login2s/new.html.erb
<h1>New login2</h1>

<%= render 'form' %>

<%= link_to 'Back', login2s_path %>

app/views/login2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @login2.userid %>
</p>

<p>
  <b>Password:</b>
  <%= @login2.password %>
</p>


<%= link_to 'Edit', edit_login2_path(@login2) %> |
<%= link_to 'Back', login2s_path %>